# Generated by Django 5.1.6 on 2025-07-14 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='periodoContable',
            fields=[
                ('idPeriodo', models.AutoField(primary_key=True, serialize=False)),
                ('nombrePeriodo', models.CharField(max_length=255)),
                ('fechaInicioPeriodo', models.DateField()),
                ('fechaFinPeriodo', models.DateField()),
                ('estadoPeriodo', models.BooleanField(default=True)),
                ('fechaPeriodoDigital', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
