# Generated by Django 5.1.6 on 2025-10-03 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('idSoli', models.AutoField(primary_key=True, serialize=False)),
                ('montoTotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estadoSolicitud', models.CharField(db_index=True, max_length=10)),
                ('fechaEntrega', models.DateField(db_index=True)),
                ('fechaSolicitud', models.DateField(auto_now_add=True)),
                ('idPersona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.personas')),
                ('idServicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.servicio')),
                ('idTramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.tramite')),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
            },
        ),
    ]
