# Generated by Django 5.1.6 on 2025-05-12 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='estadoSolicitud',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='fechaEntrega',
            field=models.DateField(db_index=True),
        ),
    ]
