# Generated by Django 5.1.6 on 2025-02-22 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Persona',
            new_name='Personas',
        ),
        migrations.AlterModelOptions(
            name='personas',
            options={'ordering': ['nombres'], 'verbose_name': 'Persona', 'verbose_name_plural': 'Personas'},
        ),
    ]
