# Generated by Django 5.1.6 on 2025-02-22 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_persona_personas_alter_personas_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Personas',
        ),
        migrations.DeleteModel(
            name='TipoPersona',
        ),
    ]
