# Generated by Django 5.1.6 on 2025-05-02 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanCuenta',
            fields=[
                ('idPlanCuenta', models.AutoField(primary_key=True, serialize=False)),
                ('codigoPlanCuenta', models.CharField(max_length=50, unique=True)),
                ('nombrePlanCuenta', models.CharField(max_length=255)),
                ('tipoPlanCuenta', models.CharField(choices=[('activo', 'Activo'), ('pasivo', 'Pasivo'), ('patrimonio', 'Patrimonio'), ('ingreso', 'Ingreso'), ('gasto', 'Gasto')], max_length=50)),
                ('nivelPlanCuenta', models.PositiveIntegerField()),
                ('estadoPlanCuenta', models.BooleanField(default=True)),
                ('fechaPlanCuenta', models.DateTimeField(auto_now_add=True)),
                ('cuentaPadre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcuentas', to='planCuenta.plancuenta')),
            ],
        ),
    ]
