# Generated by Django 5.1.6 on 2025-06-01 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanCuenta',
            fields=[
                ('idPlanCuenta', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Plan de Cuenta')),
                ('codigoPlanCuenta', models.CharField(help_text='Código jerárquico generado automáticamente', max_length=50, unique=True, verbose_name='Código de Cuenta')),
                ('nombrePlanCuenta', models.CharField(max_length=255, verbose_name='Nombre de Cuenta')),
                ('tipoPlanCuenta', models.CharField(choices=[('activo', 'Activo'), ('pasivo', 'Pasivo'), ('patrimonio', 'Patrimonio'), ('ingreso', 'Ingreso'), ('gasto', 'Gasto')], max_length=50, verbose_name='Tipo de Cuenta')),
                ('naturalezaPlanCuenta', models.CharField(blank=True, choices=[('deudora', 'Deudora'), ('acreedora', 'Acreedora')], default=None, help_text='Indica si la cuenta es deudora o acreedora. Puede cambiar en casos excepcionales.', max_length=10, null=True, verbose_name='Naturaleza de la Cuenta')),
                ('nivelPlanCuenta', models.PositiveIntegerField(help_text='1 para cuentas principales, aumenta según profundidad', verbose_name='Nivel Jerárquico')),
                ('estadoPlanCuenta', models.BooleanField(default=True, verbose_name='Estado Activo')),
                ('fechaPlanCuenta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('cuentaPadre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcuentas', to='planCuenta.plancuenta', verbose_name='Cuenta Padre')),
            ],
            options={
                'verbose_name': 'Plan de Cuenta',
                'verbose_name_plural': 'Planes de Cuenta',
                'ordering': ['codigoPlanCuenta'],
            },
        ),
    ]
