# Generated by Django 5.1.6 on 2025-11-24 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planCuenta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plancuenta',
            name='tipoPlanCuenta',
            field=models.CharField(choices=[('activo', 'Activo'), ('pasivo', 'Pasivo'), ('patrimonio', 'Patrimonio'), ('ingreso', 'Ingreso'), ('egreso', 'Egreso'), ('costos', 'Costos')], max_length=50, verbose_name='Tipo de Cuenta'),
        ),
    ]
