# Generated by Django 5.1.6 on 2025-05-17 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planCuenta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plancuenta',
            name='naturalezaPlanCuenta',
            field=models.CharField(blank=True, choices=[('deudora', 'Deudora'), ('acreedora', 'Acreedora')], default=None, help_text='Indica si la cuenta es deudora o acreedora. Puede cambiar en casos excepcionales.', max_length=10, null=True, verbose_name='Naturaleza de la Cuenta'),
        ),
    ]
