# Generated by Django 5.1.6 on 2025-11-09 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planCuenta', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='plancuenta',
            unique_together={('nombrePlanCuenta', 'nivelPlanCuenta', 'tipoPlanCuenta')},
        ),
    ]
