# Generated by Django 5.2.8 on 2025-11-23 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('periodoContable', '0001_initial'),
        ('planCuenta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaldoContable',
            fields=[
                ('idSaldo', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Saldo')),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Saldo Inicial')),
                ('saldo_final', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Saldo Final')),
                ('id_periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saldos_periodo', to='periodoContable.periodocontable', verbose_name='Periodo Contable')),
                ('id_plan_cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saldos_contables', to='planCuenta.plancuenta', verbose_name='Plan de Cuenta')),
            ],
            options={
                'verbose_name': 'Saldo Contable',
                'verbose_name_plural': 'Saldos Contables',
                'indexes': [models.Index(fields=['id_plan_cuenta', 'id_periodo'], name='saldoContab_id_plan_9c5cd7_idx')],
                'unique_together': {('id_plan_cuenta', 'id_periodo')},
            },
        ),
    ]
