# Generated by Django 5.1.6 on 2025-11-11 23:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severidad', models.CharField(choices=[('DEBUG', 'Depuración'), ('INFO', 'Informativo'), ('WARNING', 'Advertencia'), ('ERROR', 'Error'), ('CRITICAL', 'Crítico')], default='INFO', max_length=10, verbose_name='Nivel de Severidad')),
                ('accion', models.CharField(choices=[('C', 'Creación'), ('A', 'Actualización'), ('E', 'Eliminación'), ('I', 'Inicio de sesión'), ('O', 'Cierre de sesión'), ('B', 'Copia de seguridad'), ('R', 'Restauración')], max_length=1, verbose_name='Tipo de acción')),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y hora del evento')),
                ('modelo_afectado', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tabla/modulo afectado')),
                ('objeto_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID del registro afectado')),
                ('cambios', models.JSONField(blank=True, null=True, verbose_name='Detalles de cambios')),
                ('descripcion', models.TextField(verbose_name='Detalles de la acción')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('estado', models.CharField(choices=[('S', 'Éxito'), ('F', 'Fallido')], default='S', max_length=1, verbose_name='Resultado de la acción')),
            ],
            options={
                'verbose_name': 'Registro de Bitácora',
                'verbose_name_plural': 'Registros de Bitácora',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionBitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retencion', models.CharField(choices=[('diario', 'Diario (1 día)'), ('semanal', 'Semanal (7 días)'), ('mensual', 'Mensual (30 días)'), ('anual', 'Anual (365 días)'), ('personalizado', 'Personalizado')], default='anual', help_text='Período de retención para los registros de la bitácora', max_length=20)),
                ('dias_personalizados', models.PositiveIntegerField(blank=True, help_text='Días de retención para la opción personalizada', null=True)),
                ('exportar_antes_limpieza', models.BooleanField(default=True, help_text='Exportar registros antes de eliminarlos')),
                ('directorio_exportacion', models.CharField(default='backups/bitacora/', help_text='Directorio donde se guardarán los archivos exportados', max_length=255)),
                ('ultima_limpieza', models.DateTimeField(blank=True, help_text='Fecha y hora de la última limpieza automática', null=True)),
            ],
            options={
                'verbose_name': 'Configuración de Bitácora',
                'verbose_name_plural': 'Configuración de Bitácora',
            },
        ),
    ]
