# Generated by Django 5.1.6 on 2025-07-05 01:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('C', 'Creación'), ('A', 'Actualización'), ('E', 'Eliminación'), ('I', 'Inicio de sesión'), ('O', 'Cierre de sesión'), ('B', 'Copia de seguridad'), ('R', 'Restauración')], max_length=1, verbose_name='Tipo de acción')),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y hora del evento')),
                ('modelo_afectado', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tabla/modulo afectado')),
                ('objeto_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID del registro afectado')),
                ('descripcion', models.TextField(verbose_name='Detalles de la acción')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('estado', models.CharField(choices=[('S', 'Éxito'), ('F', 'Fallido')], default='S', max_length=1, verbose_name='Resultado de la acción')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacoras', to=settings.AUTH_USER_MODEL, verbose_name='Usuario involucrado')),
            ],
            options={
                'verbose_name': 'Registro de Bitácora',
                'verbose_name_plural': 'Registros de Bitácora',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
