# Generated by Django 5.1.6 on 2025-07-05 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitacora', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacora',
            name='cambios',
            field=models.JSONField(blank=True, null=True, verbose_name='Detalles de cambios'),
        ),
    ]
