# Generated by Django 5.1.6 on 2025-07-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitacora', '0002_bitacora_cambios'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacora',
            name='severidad',
            field=models.CharField(choices=[('DEBUG', 'Depuración'), ('INFO', 'Informativo'), ('WARNING', 'Advertencia'), ('ERROR', 'Error'), ('CRITICAL', 'Crítico')], default='INFO', max_length=10, verbose_name='Nivel de Severidad'),
        ),
    ]
