# Generated by Django 5.1.6 on 2025-07-07 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitacora', '0003_bitacora_severidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionBitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retencion', models.CharField(choices=[('diario', 'Diario (1 día)'), ('semanal', 'Semanal (7 días)'), ('mensual', 'Mensual (30 días)'), ('anual', 'Anual (365 días)'), ('personalizado', 'Personalizado')], default='anual', help_text='Período de retención para los registros de la bitácora', max_length=20)),
                ('dias_personalizados', models.PositiveIntegerField(blank=True, help_text='Días de retención para la opción personalizada', null=True)),
                ('exportar_antes_limpieza', models.BooleanField(default=True, help_text='Exportar registros antes de eliminarlos')),
                ('directorio_exportacion', models.CharField(default='backups/bitacora/', help_text='Directorio donde se guardarán los archivos exportados', max_length=255)),
                ('ultima_limpieza', models.DateTimeField(blank=True, help_text='Fecha y hora de la última limpieza automática', null=True)),
            ],
            options={
                'verbose_name': 'Configuración de Bitácora',
                'verbose_name_plural': 'Configuración de Bitácora',
            },
        ),
    ]
