# Generated by Django 5.1.6 on 2025-06-25 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
        ('inscripcion', '0001_initial'),
        ('solicitud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisitoCliente',
            fields=[
                ('idRC', models.AutoField(primary_key=True, serialize=False)),
                ('entregado', models.BooleanField(default=False)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaModificado', models.DateTimeField(auto_now=True)),
                ('idInscripcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inscripcion.inscripcion')),
                ('idRequisito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.requisito')),
                ('idSolicitud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='solicitud.solicitud')),
            ],
            options={
                'verbose_name': 'Requisito de Cliente',
                'verbose_name_plural': 'Requisitos de Cliente',
            },
        ),
    ]
