# Generated by Django 5.1.6 on 2025-10-04 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('idInscripcion', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('fechaInscripcion', models.DateField(auto_now_add=True)),
                ('estadoPago', models.CharField(choices=[('SIN CONFIRMAR', 'Sin Confirmar '), ('PENDIENTE', 'Pendiente'), ('PARCIAL', 'Pago Parcial'), ('PAGADO', 'Pago Completo'), ('FACTURADO', 'Factura creada')], default='PENDIENTE', max_length=20)),
                ('montoPagado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('idCohorte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.cohorte')),
                ('idFormacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.formacion')),
                ('idPersona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.personas')),
                ('idTF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.tipoformacion')),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Inscripciones',
            },
        ),
        migrations.CreateModel(
            name='InscripcionCuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estadoPago', models.CharField(choices=[('SIN CONFIRMAR', 'Sin Confirmar '), ('EN ESPERA', 'En Espera'), ('PENDIENTE', 'Pendiente'), ('PARCIAL', 'Pago Parcial'), ('PAGADO', 'Pagado'), ('FACTURADO', 'Factura Creada')], default='PENDIENTE', max_length=20)),
                ('montoPagado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fechaPago', models.DateField(blank=True, null=True)),
                ('idCuota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.cuotaformacion')),
                ('idInscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripcion.inscripcion')),
            ],
            options={
                'verbose_name': 'Cuota de Inscripción',
                'verbose_name_plural': 'Cuotas de Inscripción',
            },
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='cuotas',
            field=models.ManyToManyField(related_name='inscripciones', through='inscripcion.InscripcionCuota', to='home.cuotaformacion'),
        ),
    ]
