# Generated by Django 5.1.6 on 2025-05-29 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
        ('persona', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('idInscripcion', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('fechaInscripcion', models.DateField(auto_now_add=True)),
                ('idCohorte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.cohorte')),
                ('idFormacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.formacion')),
                ('idPersona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.personas')),
                ('idTF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.tipoformacion')),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Inscripciones',
            },
        ),
    ]
