# Generated by Django 5.1.6 on 2025-07-08 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('idInscripcion', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('fechaInscripcion', models.DateField(auto_now_add=True)),
                ('estadoPago', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PARCIAL', 'Pago Parcial'), ('COMPLETO', 'Pago Completo')], default='PENDIENTE', max_length=20)),
                ('montoPagado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('idCohorte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.cohorte')),
                ('idFormacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.formacion')),
                ('idPersona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.personas')),
                ('idTF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.tipoformacion')),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Inscripciones',
            },
        ),
    ]
