# Generated by Django 5.1.6 on 2025-10-19 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscripcion',
            name='idFormacion',
        ),
        migrations.RemoveField(
            model_name='inscripcion',
            name='idTF',
        ),
    ]
