# Generated by Django 5.1.6 on 2025-06-29 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0002_initial'),
        ('home', '0002_remove_formacion_valorformacion_and_more'),
        ('inscripcion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='estadoPago',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PARCIAL', 'Pago Parcial'), ('COMPLETO', 'Pago Completo')], default='PENDIENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='montoPagado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='CuotaFormacion',
            fields=[
                ('idCuota', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCuota', models.CharField(max_length=100)),
                ('tipoCuota', models.CharField(choices=[('MENSUAL', 'Mensual'), ('BIMESTRAL', 'Bimestral'), ('TRIMESTRAL', 'Trimestral'), ('SEMESTRAL', 'Semestral'), ('ANUAL', 'Anual'), ('UNICA', 'Única')], max_length=20)),
                ('valorCuota', models.DecimalField(decimal_places=2, max_digits=10)),
                ('orden', models.PositiveIntegerField(help_text='Orden en que se deben pagar las cuotas')),
                ('fechaVencimiento', models.DateField(blank=True, help_text='Fecha de vencimiento para esta cuota', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('idFormacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='home.formacion')),
            ],
            options={
                'verbose_name': 'Cuota de Formación',
                'verbose_name_plural': 'Cuotas de Formación',
                'ordering': ['idFormacion', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='PagoCuota',
            fields=[
                ('idPagoCuota', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fechaPago', models.DateField(blank=True, null=True)),
                ('fechaVencimiento', models.DateField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('VENCIDO', 'Vencido'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('idCuota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripcion.cuotaformacion')),
                ('idInscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_cuota', to='inscripcion.inscripcion')),
                ('idNota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_cuota', to='factura.nota')),
            ],
            options={
                'verbose_name': 'Pago de Cuota',
                'verbose_name_plural': 'Pagos de Cuotas',
            },
        ),
    ]
