# Generated by Django 5.1.6 on 2025-07-12 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='estadoPago',
            field=models.CharField(choices=[('SIN CONFIRMAR', 'Sin Confirmar '), ('PENDIENTE', 'Pendiente'), ('PARCIAL', 'Pago Parcial'), ('PAGADO', 'Pago Completo'), ('FACTURADO', 'Factura creada')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='inscripcioncuota',
            name='estadoPago',
            field=models.CharField(choices=[('SIN CONFIRMAR', 'Sin Confirmar '), ('EN ESPERA', 'En Espera'), ('PENDIENTE', 'Pendiente'), ('PARCIAL', 'Pago Parcial'), ('PAGADO', 'Pagado'), ('FACTURADO', 'Factura Creada')], default='PENDIENTE', max_length=20),
        ),
    ]
