# Generated by Django 5.1.6 on 2025-06-29 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_cuotaformacion'),
        ('inscripcion', '0002_inscripcion_estadopago_inscripcion_montopagado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagocuota',
            name='idCuota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.cuotaformacion'),
        ),
        migrations.DeleteModel(
            name='CuotaFormacion',
        ),
    ]
