# Generated by Django 5.1.6 on 2025-06-30 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0003_alter_pagocuota_idcuota_delete_cuotaformacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagocuota',
            name='fechaPago',
        ),
        migrations.RemoveField(
            model_name='pagocuota',
            name='fechaVencimiento',
        ),
        migrations.AddField(
            model_name='pagocuota',
            name='fecha',
            field=models.DateField(auto_now=True),
        ),
    ]
