# Generated by Django 5.1.6 on 2025-07-06 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0004_remove_pagocuota_fechapago_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PagoCuota',
        ),
    ]
