# Generated by Django 5.1.6 on 2025-07-08 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_cuotaformacion_fechacuota'),
        ('inscripcion', '0005_delete_pagocuota'),
    ]

    operations = [
        migrations.CreateModel(
            name='InscripcionCuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estadoPago', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('PARCIAL', 'Pago Parcial')], default='PENDIENTE', max_length=20)),
                ('montoPagado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fechaPago', models.DateField(blank=True, null=True)),
                ('idCuota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.cuotaformacion')),
                ('idInscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripcion.inscripcion')),
            ],
            options={
                'verbose_name': 'Cuota de Inscripción',
                'verbose_name_plural': 'Cuotas de Inscripción',
            },
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='cuotas',
            field=models.ManyToManyField(related_name='inscripciones', through='inscripcion.InscripcionCuota', to='home.cuotaformacion'),
        ),
    ]
