# Generated by Django 5.2.8 on 2025-11-23 05:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('usuario', models.CharField(blank=True, max_length=150, null=True)),
                ('tipo', models.CharField(choices=[('full', 'Full'), ('data-only', 'Data only'), ('wal', 'WAL')], db_index=True, max_length=20)),
                ('checksum', models.CharField(blank=True, max_length=128, null=True)),
                ('ruta_storage', models.TextField()),
                ('notas', models.TextField(blank=True, null=True)),
                ('tamaño', models.BigIntegerField(default=0)),
                ('expiracion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='BackupAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(blank=True, max_length=150, null=True)),
                ('action', models.CharField(choices=[('create', 'Create'), ('delete', 'Delete'), ('restore', 'Restore')], max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, null=True)),
                ('backup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='backup.backup')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='BackupTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('error', 'Error')], default='pending', max_length=20)),
                ('result', models.TextField(blank=True, null=True)),
                ('task_id', models.CharField(blank=True, max_length=64, null=True)),
                ('usuario', models.CharField(blank=True, max_length=150, null=True)),
                ('backup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='backup.backup')),
            ],
        ),
    ]
