# Generated by Django 5.1.6 on 2025-04-16 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('idPersona', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=10)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('correo', models.EmailField(max_length=254)),
                ('estadoPersona', models.CharField(max_length=10)),
                ('fechaPersona', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'ordering': ['idPersona'],
            },
        ),
        migrations.CreateModel(
            name='TipoPersona',
            fields=[
                ('idTP', models.AutoField(primary_key=True, serialize=False)),
                ('nombreTP', models.CharField(max_length=100)),
                ('estadoTP', models.CharField(max_length=10)),
                ('fechaTP', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo de Persona',
                'verbose_name_plural': 'Tipos de Personas',
            },
        ),
        migrations.CreateModel(
            name='PersonaTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaAsignacion', models.DateField(auto_now_add=True)),
                ('idPersona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.personas')),
                ('idTP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.tipopersona')),
            ],
            options={
                'verbose_name': 'Asignación de Tipo a Persona',
                'verbose_name_plural': 'Asignaciones de Tipos a Personas',
                'unique_together': {('idPersona', 'idTP')},
            },
        ),
    ]
