# Generated by Django 5.1.6 on 2025-04-29 11:42

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='cedula',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AddConstraint(
            model_name='tipopersona',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('nombreTP'), name='unique_nombreTP_insensitive'),
        ),
    ]
