# Generated by Django 5.1.6 on 2025-05-31 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personas',
            name='direccion',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='personas',
            name='rif',
            field=models.CharField(blank=True, help_text='Formato: J-XXXXXXXX-X', max_length=20, null=True, unique=True),
        ),
    ]
