# Generated by Django 5.1.6 on 2025-06-01 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_personas_direccion_personas_rif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='cedula',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
