# Generated by Django 5.1.6 on 2025-05-11 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0006_alter_moneda_options'),
        ('planCuenta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('idBanco', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Banco')),
                ('nombreBanco', models.CharField(max_length=100, verbose_name='Nombre del Banco')),
                ('codLocalBanco', models.CharField(max_length=10, unique=True, verbose_name='Código Local')),
                ('codSwiftBanco', models.CharField(max_length=11, unique=True, verbose_name='Código SWIFT/BIC')),
                ('tipoCuenta', models.CharField(choices=[('activo', 'Activo (Cuentas corrientes, de ahorro, etc.)'), ('pasivo', 'Pasivo (Préstamos, créditos, sobregiros)'), ('patrimonio', 'Patrimonio (Fondos de inversión)')], default='activo', max_length=20, verbose_name='Tipo de Cuenta Contable')),
                ('estadoBanco', models.BooleanField(default=True, verbose_name='Activo')),
                ('fechaBanco', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('codigoPlanCuenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bancos', to='planCuenta.plancuenta', verbose_name='Cuenta Contable Asociada')),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
                'ordering': ['nombreBanco'],
            },
        ),
        migrations.CreateModel(
            name='CuentaBanco',
            fields=[
                ('idCuentaBanco', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Cuenta Bancaria')),
                ('numeroCuentaBanco', models.CharField(max_length=20, unique=True, verbose_name='Número de Cuenta')),
                ('tipoCuenta', models.CharField(choices=[('activo', 'Activo'), ('pasivo', 'Pasivo'), ('patrimonio', 'Patrimonio')], max_length=20, verbose_name='Tipo Contable')),
                ('tipoProducto', models.CharField(choices=[('corriente', 'Cuenta Corriente'), ('ahorro', 'Cuenta de Ahorro'), ('plazo_fijo', 'Depósito a Plazo Fijo'), ('prestamo', 'Préstamo'), ('credito', 'Línea de Crédito'), ('inversion', 'Fondo de Inversión')], default='corriente', max_length=20, verbose_name='Tipo de Producto')),
                ('fechaApertura', models.DateField(verbose_name='Fecha de Apertura')),
                ('saldoDisponible', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Saldo Disponible')),
                ('fechaRegistro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('fechaActualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('estado', models.BooleanField(default=True, verbose_name='Activa')),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuentaBanco.banco', verbose_name='Banco')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.moneda', verbose_name='Moneda')),
                ('planCuenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planCuenta.plancuenta', verbose_name='Cuenta Contable Asociada')),
            ],
            options={
                'verbose_name': 'Cuenta Bancaria',
                'verbose_name_plural': 'Cuentas Bancarias',
                'ordering': ['banco__nombreBanco', 'numeroCuentaBanco'],
            },
        ),
    ]
