# Generated by Django 5.1.6 on 2025-05-04 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0005_alter_banco_nombrebanco_alter_cargo_nombrecargo_and_more'),
        ('planCuenta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cuentaBanco',
            fields=[
                ('idCuentaBanco', models.AutoField(primary_key=True, serialize=False)),
                ('numeroCuentaBanco', models.CharField(max_length=20, unique=True)),
                ('tipoCuentaBanco', models.CharField(max_length=50)),
                ('fechaApertura', models.DateField()),
                ('saldoDisponible', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fechaRegistroCB', models.DateTimeField(auto_now_add=True)),
                ('fechaActualizadoCB', models.DateTimeField(auto_now=True)),
                ('estadoCB', models.BooleanField(default=True)),
                ('idBanco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.banco')),
                ('idMoneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.moneda')),
                ('idPlanCuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planCuenta.plancuenta')),
            ],
        ),
    ]
