# Generated by Django 5.1.6 on 2025-05-11 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentaBanco', '0001_initial'),
        ('planCuenta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banco',
            name='tipoCuenta',
        ),
        migrations.RemoveField(
            model_name='cuentabanco',
            name='tipoCuenta',
        ),
        migrations.AddField(
            model_name='banco',
            name='cuentaPadre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bancos_hijos', to='planCuenta.plancuenta', verbose_name='Cuenta Contable Padre'),
            preserve_default=False,
        ),
    ]
