# Generated by Django 5.1.6 on 2025-05-31 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuentaBanco', '0001_initial'),
        ('home', '0001_initial'),
        ('planCuenta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentabanco',
            name='moneda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.moneda', verbose_name='Moneda'),
        ),
        migrations.AddField(
            model_name='cuentabanco',
            name='planCuenta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planCuenta.plancuenta', verbose_name='Cuenta Contable Asociada'),
        ),
    ]
