# Generated by Django 5.1.6 on 2025-05-10 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentaBanco', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentabanco',
            name='tipoCuentaBanco',
            field=models.CharField(choices=[('ahorro', 'Ahorro'), ('corriente', 'Corriente')], max_length=50),
        ),
    ]
