# Generated by Django 3.2.6 on 2025-03-03 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('idCargo', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCargo', models.CharField(max_length=100)),
                ('estadoCargo', models.CharField(max_length=10)),
                ('fechaCargo', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
            },
        ),
        migrations.CreateModel(
            name='Cohorte',
            fields=[
                ('idCohorte', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCohorte', models.CharField(max_length=100)),
                ('estadoCohorte', models.CharField(max_length=10)),
                ('fechaCohorte', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cohorte',
                'verbose_name_plural': 'Cohortes',
            },
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('idCuota', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCuota', models.CharField(max_length=100)),
                ('estadoCuota', models.CharField(max_length=10)),
                ('fechaCuota', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cuota',
                'verbose_name_plural': 'Cuotas',
            },
        ),
        migrations.CreateModel(
            name='TipoPersona',
            fields=[
                ('idTP', models.AutoField(primary_key=True, serialize=False)),
                ('nombreTP', models.CharField(max_length=100)),
                ('estadoTP', models.CharField(max_length=10)),
                ('fechaTP', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo de Persona',
                'verbose_name_plural': 'Tipos de Personas',
            },
        ),
        migrations.CreateModel(
            name='TipoOferta',
            fields=[
                ('idTipoOferta', models.AutoField(primary_key=True, serialize=False)),
                ('nombreTipoOferta', models.CharField(max_length=100)),
                ('estadoTipoOferta', models.CharField(max_length=10)),
                ('fechaTipoOferta', models.DateField(auto_now_add=True)),
                ('idCuota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.cuota')),
            ],
            options={
                'verbose_name': 'Tipo de Oferta',
                'verbose_name_plural': 'Tipos de Ofertas',
            },
        ),
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('idPersona', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=10)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('correo', models.EmailField(max_length=254)),
                ('estadoPersona', models.CharField(max_length=10)),
                ('fechaPersona', models.DateField(auto_now_add=True)),
                ('idTP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.tipopersona')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'ordering': ['idTP'],
            },
        ),
        migrations.CreateModel(
            name='Ofertas',
            fields=[
                ('idOferta', models.AutoField(primary_key=True, serialize=False)),
                ('nombreOferta', models.CharField(max_length=100)),
                ('duracion', models.CharField(max_length=100)),
                ('estadoOferta', models.CharField(max_length=10)),
                ('fechaOferta', models.DateField(auto_now_add=True)),
                ('idTipoOferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.tipooferta')),
            ],
            options={
                'verbose_name': 'Oferta',
                'verbose_name_plural': 'Ofertas',
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('idMateria', models.AutoField(primary_key=True, serialize=False)),
                ('nombreMateria', models.CharField(max_length=100)),
                ('estadoMateria', models.CharField(max_length=10)),
                ('fechaMateria', models.DateField(auto_now_add=True)),
                ('idOferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ofertas')),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('idContrato', models.AutoField(primary_key=True, serialize=False)),
                ('estadoContrato', models.CharField(max_length=10)),
                ('fechaContrato', models.DateField(auto_now_add=True)),
                ('idCargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.cargo')),
                ('idCohorte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.cohorte')),
                ('idMateria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.materia')),
                ('idPersona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.personas')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
            },
        ),
    ]
