# Generated by Django 5.1.6 on 2025-04-25 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='usuarios_set', related_query_name='usuario', to='auth.group', verbose_name='Grupos'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='usuarios_set', related_query_name='usuario', to='auth.permission', verbose_name='Permisos de usuario'),
        ),
    ]
