# Generated by Django 5.1.6 on 2025-03-09 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('idIngreso', models.AutoField(primary_key=True, serialize=False)),
                ('montoIngreso', models.DecimalField(decimal_places=2, max_digits=10)),
                ('referencia', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('estadoIngreso', models.CharField(max_length=10)),
                ('fechaIngreso', models.DateField(auto_now_add=True)),
                ('idBanco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.banco')),
                ('idDenominacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.denominacion')),
                ('idTasa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.tasa')),
                ('idTipoIngreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.tipoingreso')),
            ],
            options={
                'verbose_name': 'Ingreso',
                'verbose_name_plural': 'Ingresos',
            },
        ),
    ]
