# Generated by Django 5.1.6 on 2025-03-23 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ofertas',
            new_name='Formacion',
        ),
        migrations.RenameModel(
            old_name='TipoOferta',
            new_name='TipoFormacion',
        ),
        migrations.AlterModelOptions(
            name='formacion',
            options={'verbose_name': 'Formacion', 'verbose_name_plural': 'Formaciones'},
        ),
        migrations.AlterModelOptions(
            name='tipoformacion',
            options={'verbose_name': 'TipoFormación', 'verbose_name_plural': 'TiposFormacion'},
        ),
        migrations.RenameField(
            model_name='formacion',
            old_name='estadoOferta',
            new_name='estadoFormacion',
        ),
        migrations.RenameField(
            model_name='formacion',
            old_name='fechaOferta',
            new_name='fechaFormacion',
        ),
        migrations.RenameField(
            model_name='formacion',
            old_name='idOferta',
            new_name='idFormacion',
        ),
        migrations.RenameField(
            model_name='formacion',
            old_name='idTipoOferta',
            new_name='idTF',
        ),
        migrations.RenameField(
            model_name='formacion',
            old_name='nombreOferta',
            new_name='nombreFormacion',
        ),
        migrations.RenameField(
            model_name='tipoformacion',
            old_name='estadoTipoOferta',
            new_name='estadoTipoFormacion',
        ),
        migrations.RenameField(
            model_name='tipoformacion',
            old_name='fechaTipoOferta',
            new_name='fechaTipoFormacion',
        ),
        migrations.RenameField(
            model_name='tipoformacion',
            old_name='idTipoOferta',
            new_name='idTF',
        ),
        migrations.RenameField(
            model_name='tipoformacion',
            old_name='nombreTipoOferta',
            new_name='nombreTipoFormacion',
        ),
        migrations.RemoveField(
            model_name='materia',
            name='idOferta',
        ),
        migrations.AddField(
            model_name='materia',
            name='idFormacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.tipoformacion'),
            preserve_default=False,
        ),
    ]
