# Generated by Django 5.1.6 on 2025-03-05 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Honorario',
            fields=[
                ('idHonorario', models.AutoField(primary_key=True, serialize=False)),
                ('horas', models.FloatField()),
                ('estadoContrato', models.CharField(max_length=10)),
                ('fechaContrato', models.DateField(auto_now_add=True)),
                ('idContrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.contrato')),
            ],
            options={
                'verbose_name': 'Honorario',
                'verbose_name_plural': 'Honorarios',
            },
        ),
    ]
