# Generated by Django 5.1.6 on 2025-03-30 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='idTipoMovimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.tipomovimiento'),
        ),
    ]
