# Generated by Django 5.1.6 on 2025-04-15 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='configuracion',
            table=None,
        ),
    ]
