# Generated by Django 5.1.6 on 2025-03-07 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tramite',
            fields=[
                ('idTramite', models.AutoField(primary_key=True, serialize=False)),
                ('nombreTramite', models.CharField(max_length=100)),
                ('diasTramite', models.CharField(max_length=100)),
                ('precioTramite', models.CharField(max_length=100)),
                ('estadoTramite', models.CharField(max_length=10)),
                ('fechaTramite', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tramite',
                'verbose_name_plural': 'Tramites',
            },
        ),
    ]
