# Generated by Django 5.1.6 on 2025-03-28 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='idBanco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.banco'),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='referencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
