# Generated by Django 5.1.6 on 2025-06-29 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formacion',
            name='valorFormacion',
        ),
        migrations.AddField(
            model_name='formacion',
            name='tieneCuotas',
            field=models.BooleanField(default=False, verbose_name='Tiene sistema de cuotas?'),
        ),
        migrations.AddField(
            model_name='formacion',
            name='valorInscripcion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor de Inscripción'),
        ),
    ]
