# Generated by Django 5.1.6 on 2025-03-05 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisito',
            fields=[
                ('idRequisito', models.AutoField(primary_key=True, serialize=False)),
                ('nombreRequisito', models.CharField(max_length=100)),
                ('estadoRequisito', models.CharField(max_length=10)),
                ('fechaRequisito', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Requisito',
                'verbose_name_plural': 'Requisitos',
            },
        ),
    ]
