# Generated by Django 5.1.6 on 2025-04-04 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='contrasenia',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='estadoUsuario',
        ),
        migrations.AlterModelTable(
            name='usuarios',
            table=None,
        ),
    ]
