# Generated by Django 3.2.6 on 2025-02-23 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('idCuota', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCuota', models.CharField(max_length=100)),
                ('estadoCuota', models.CharField(max_length=10)),
                ('fechaCuota', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cuota',
                'verbose_name_plural': 'Cuotas',
            },
        ),
        migrations.CreateModel(
            name='TipoOferta',
            fields=[
                ('idTipoOferta', models.AutoField(primary_key=True, serialize=False)),
                ('nombreTipoOferta', models.CharField(max_length=100)),
                ('estadoTipoOferta', models.CharField(max_length=10)),
                ('fechaTipoOferta', models.DateField(auto_now_add=True)),
                ('idCuota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.cuota')),
            ],
            options={
                'verbose_name': 'Tipo de Oferta',
                'verbose_name_plural': 'Tipos de Ofertas',
            },
        ),
        migrations.CreateModel(
            name='Ofertas',
            fields=[
                ('idOferta', models.AutoField(primary_key=True, serialize=False)),
                ('nombreOferta', models.CharField(max_length=100)),
                ('duración', models.CharField(max_length=100)),
                ('estadoOferta', models.CharField(max_length=10)),
                ('fechaOferta', models.DateField(auto_now_add=True)),
                ('idTipoOferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.tipooferta')),
            ],
            options={
                'verbose_name': 'Oferta',
                'verbose_name_plural': 'Ofertas',
            },
        ),
    ]
