# Generated by Django 5.1.6 on 2025-03-07 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Denominacion',
            fields=[
                ('idDenominacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombreDenominacion', models.CharField(max_length=100)),
                ('estadoDenominacion', models.CharField(max_length=10)),
                ('fechaDenominacion', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Denominacion',
                'verbose_name_plural': 'Denominaciones',
            },
        ),
    ]
