# Generated by Django 5.1.6 on 2025-02-22 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipopersona',
            name='estadoTP',
            field=models.CharField(max_length=10),
        ),
    ]
