# Generated by Django 5.1.6 on 2025-10-18 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_configuracion_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohorte',
            name='fechaFin',
            field=models.DateField(default="2025-10-17"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cohorte',
            name='fechaInicio',
            field=models.DateField(default="2024-10-17"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cohorte',
            name='lapsoInscripcion',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Lapso de inscripción'),
            preserve_default=False,
        ),
    ]
