# Generated by Django 5.1.6 on 2025-03-28 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_ofertas_formacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipoformacion',
            name='idCuota',
        ),
    ]
