# Generated by Django 5.1.6 on 2025-04-17 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_configuracion_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moneda',
            options={'ordering': ['nombreMoneda'], 'verbose_name': 'Moneda', 'verbose_name_plural': 'Monedas'},
        ),
        migrations.AlterField(
            model_name='moneda',
            name='simboloMoneda',
            field=models.CharField(db_index=True, max_length=5, unique=True),
        ),
    ]
