# Generated by Django 5.1.6 on 2025-03-07 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_denominacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('idBanco', models.AutoField(primary_key=True, serialize=False)),
                ('nombreBanco', models.CharField(max_length=100)),
                ('codBanco', models.CharField(max_length=100)),
                ('codContable', models.CharField(max_length=100)),
                ('estadoBanco', models.CharField(max_length=10)),
                ('fechaBanco', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
            },
        ),
    ]
