# Generated by Django 5.1.6 on 2025-10-18 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_configuracion_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohorte',
            name='fechaFin',
            field=models.DateField(default='2023-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cohorte',
            name='fechaInicio',
            field=models.DateField(default='2022-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cohorte',
            name='idFormacion',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, related_name='cohortes', to='home.formacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cohorte',
            name='lapsoInscripcion',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='Lapso de inscripción'),
            preserve_default=False,
        ),
    ]
