# Generated by Django 5.1.6 on 2025-06-29 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_formacion_valorformacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuotaFormacion',
            fields=[
                ('idCuota', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCuota', models.CharField(max_length=100)),
                ('tipoCuota', models.CharField(choices=[('MENSUAL', 'Mensual'), ('BIMESTRAL', 'Bimestral'), ('TRIMESTRAL', 'Trimestral'), ('SEMESTRAL', 'Semestral'), ('ANUAL', 'Anual'), ('UNICA', 'Única')], max_length=20)),
                ('valorCuota', models.DecimalField(decimal_places=2, max_digits=10)),
                ('orden', models.PositiveIntegerField(help_text='Orden en que se deben pagar las cuotas')),
                ('fechaCuota', models.DateField(blank=True, help_text='Fecha de vencimiento para esta cuota', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('idFormacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='home.formacion')),
            ],
            options={
                'verbose_name': 'Cuota de Formación',
                'verbose_name_plural': 'Cuotas de Formación',
                'ordering': ['idFormacion', 'orden'],
            },
        ),
    ]
