# Generated by Django 5.1.6 on 2025-04-05 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_usuarios_contrasenia_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuarios',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
    ]
