# Generated by Django 3.2.6 on 2025-02-24 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_cuota_ofertas_tipooferta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ofertas',
            old_name='duración',
            new_name='duracion',
        ),
        migrations.RenameField(
            model_name='personas',
            old_name='fecha',
            new_name='fechaPersona',
        ),
    ]
