# Generated by Django 3.2.6 on 2025-02-25 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20250224_0625'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('idMateria', models.AutoField(primary_key=True, serialize=False)),
                ('nombreMateria', models.CharField(max_length=100)),
                ('estadoMateria', models.CharField(max_length=10)),
                ('fechaMateria', models.DateField(auto_now_add=True)),
                ('idOferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ofertas')),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
            },
        ),
    ]
