# Generated by Django 5.1.6 on 2025-04-17 21:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_moneda_options_alter_moneda_simbolomoneda'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banco',
            options={'ordering': ['nombreBanco'], 'verbose_name': 'Banco', 'verbose_name_plural': 'Bancos'},
        ),
        migrations.AlterField(
            model_name='banco',
            name='codBanco',
            field=models.CharField(db_index=True, max_length=4, unique=True, verbose_name='Código SUDEBAN'),
        ),
        migrations.AlterField(
            model_name='banco',
            name='codContable',
            field=models.CharField(default='0000', max_length=10, verbose_name='Código Contable'),
        ),
        migrations.AlterField(
            model_name='banco',
            name='estadoBanco',
            field=models.CharField(default='ACTIVO', max_length=10, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='banco',
            name='fechaBanco',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha Registro'),
        ),
        migrations.AlterField(
            model_name='banco',
            name='nombreBanco',
            field=models.CharField(max_length=150, verbose_name='Nombre del Banco'),
        ),
    ]
