# Generated by Django 5.1.6 on 2025-03-08 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_banco'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('idMoneda', models.AutoField(primary_key=True, serialize=False)),
                ('nombreMoneda', models.CharField(max_length=100)),
                ('simboloMoneda', models.CharField(max_length=5)),
                ('estadoMoneda', models.CharField(max_length=10)),
                ('fechaMoneda', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Moneda',
                'verbose_name_plural': 'Monedas',
            },
        ),
    ]
