# Generated by Django 5.1.6 on 2025-04-26 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('home', '0003_alter_usuarios_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Grupos a los que pertenece el usuario.', related_name='usuarios_grupos', to='auth.group', verbose_name='Grupos'),
        ),
    ]
