# Generated by Django 5.1.6 on 2025-10-19 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_cohorte_fechafin_cohorte_fechainicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohorte',
            name='nombreCohorte',
            field=models.CharField(max_length=100),
        ),
    ]
