# Generated by Django 5.1.6 on 2025-06-30 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_cuotaformacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuotaformacion',
            name='fechaCuota',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
