# Generated by Django 5.1.6 on 2025-03-29 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_tipoformacion_idcuota'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoformacion',
            name='cuotas',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
