# Generated by Django 5.1.6 on 2025-03-30 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_movimiento_idtipomovimiento'),
        ('home', '0004_tipoformacion_cuotas'),
    ]

    operations = [
    ]
