# Generated by Django 5.1.6 on 2025-10-31 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentaBanco', '0002_initial'),
        ('home', '0004_alter_cohorte_nombrecohorte'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisito',
            name='app',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ConfiguracionApp',
            fields=[
                ('idAppConfig', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Configuración App')),
                ('cedulaCuenta', models.CharField(max_length=20, verbose_name='Cédula de la Cuenta')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado de la Configuración')),
                ('fechaAppConfig', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Configuración de la App')),
                ('idCuentaBanco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cuentaBanco.cuentabanco', verbose_name='Cuenta Bancaria Asociada')),
            ],
            options={
                'verbose_name': 'Configuración de la App',
                'verbose_name_plural': 'Configuraciones de la App',
            },
        ),
    ]
