# Generated by Django 3.2.6 on 2025-03-03 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_materia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cohorte',
            fields=[
                ('idCohorte', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCohorte', models.CharField(max_length=100)),
                ('estadoCohorte', models.CharField(max_length=10)),
                ('fechaCohorte', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cohorte',
                'verbose_name_plural': 'Cohortes',
            },
        ),
    ]
