# Generated by Django 5.1.6 on 2025-03-08 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_moneda'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasa',
            fields=[
                ('idTasa', models.AutoField(primary_key=True, serialize=False)),
                ('montoTasa', models.CharField(max_length=100)),
                ('estadoTasa', models.CharField(max_length=10)),
                ('fechaTasa', models.DateField(auto_now_add=True)),
                ('idMoneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.moneda')),
            ],
            options={
                'verbose_name': 'Tasa',
                'verbose_name_plural': 'Tasas',
            },
        ),
    ]
