# Generated by Django 5.1.6 on 2025-04-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_usuarios_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banco',
            name='nombreBanco',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nombre del Banco'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='nombreCargo',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='cohorte',
            name='nombreCohorte',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='nombreInstitucion',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nombre de la Institución'),
        ),
        migrations.AlterField(
            model_name='denominacion',
            name='nombreDenominacion',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='formacion',
            name='nombreFormacion',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='materia',
            name='nombreMateria',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='moneda',
            name='nombreMoneda',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='requisito',
            name='nombreRequisito',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='nombreServicio',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='tipoformacion',
            name='nombreTipoFormacion',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='tipoingreso',
            name='nombreTipoIngreso',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='tipomovimiento',
            name='nombreTipoMovimiento',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='nombreTramite',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
