# Generated by Django 3.2.6 on 2025-03-03 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_cohorte'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('idCargo', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCargo', models.CharField(max_length=100)),
                ('estadoCargo', models.CharField(max_length=10)),
                ('fechaCargo', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
            },
        ),
    ]
