# Generated by Django 5.1.6 on 2025-05-05 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_banco_nombrebanco_alter_cargo_nombrecargo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moneda',
            options={},
        ),
    ]
