# Generated by Django 5.1.6 on 2025-10-31 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentaBanco', '0002_initial'),
        ('home', '0005_requisito_app_configuracionapp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisito',
            name='app',
        ),
        migrations.AddField(
            model_name='configuracion',
            name='cedulaCuenta',
            field=models.CharField(default=1, max_length=20, verbose_name='Cédula de la Cuenta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configuracion',
            name='idCuentaBanco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cuentaBanco.cuentabanco', verbose_name='Cuenta Bancaria Asociada'),
        ),
        migrations.DeleteModel(
            name='ConfiguracionApp',
        ),
    ]
