# Generated by Django 5.1.6 on 2025-05-04 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_banco_nombrebanco_alter_cargo_nombrecargo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasa',
            name='idMoneda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasas', to='home.moneda'),
        ),
    ]
