# Generated by Django 5.1.6 on 2025-03-08 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_tasa'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoIngreso',
            fields=[
                ('idTipoIngreso', models.AutoField(primary_key=True, serialize=False)),
                ('nombreTipoIngreso', models.CharField(max_length=100)),
                ('estadoTipoIngreso', models.CharField(max_length=10)),
                ('fechaTipoIngreso', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'TipoIngreso',
                'verbose_name_plural': 'TipoIngresos',
            },
        ),
    ]
