# Generated by Django 3.2.6 on 2025-03-03 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('idContrato', models.AutoField(primary_key=True, serialize=False)),
                ('estadoContrato', models.CharField(max_length=10)),
                ('fechaContrato', models.DateField(auto_now_add=True)),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.personas')),
                ('idCargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.cargo')),
                ('idCohorte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.cohorte')),
                ('idMateria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.materia')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
            },
        ),
    ]
