# Generated by Django 5.1.6 on 2025-11-01 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_requisito_app_configuracion_cedulacuenta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisito',
            name='app',
            field=models.BooleanField(default=False),
        ),
    ]
