# Generated by Django 5.1.6 on 2025-05-11 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_tasa_idmoneda'),
        ('persona', '0002_alter_personas_cedula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='idPersona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='persona.personas'),
        ),
    ]
