# Generated by Django 3.2.6 on 2025-03-03 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20250303_0709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contrato',
            old_name='id',
            new_name='idPersona',
        ),
        migrations.RenameField(
            model_name='personas',
            old_name='id',
            new_name='idPersona',
        ),
    ]
