# Generated by Django 5.1.6 on 2025-05-12 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_usuarios_idpersona'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicio',
            options={},
        ),
        migrations.AlterField(
            model_name='cohorte',
            name='estadoCohorte',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='cohorte',
            name='fechaCohorte',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='estadoServicio',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='fechaServicio',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='servicio',
            index=models.Index(fields=['estadoServicio', 'nombreServicio'], name='home_servic_estadoS_acba66_idx'),
        ),
    ]
