# Generated by Django 5.1.6 on 2025-05-12 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_moneda_options'),
        ('home', '0008_alter_servicio_options_alter_cohorte_estadocohorte_and_more'),
    ]

    operations = [
    ]
