# Generated by Django 5.1.6 on 2025-05-28 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_merge_20250512_1604'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tasa',
            unique_together={('idMoneda', 'montoTasa', 'fechaTasa')},
        ),
    ]
