# Generated by Django 5.1.6 on 2025-05-28 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_tasa_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moneda',
            options={'ordering': ['nombreMoneda'], 'verbose_name': 'Moneda', 'verbose_name_plural': 'Monedas'},
        ),
    ]
