# Generated by Django 5.1.6 on 2025-07-15 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('periodoContable', '0001_initial'),
        ('planCuenta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsientoContable',
            fields=[
                ('idAsiento', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Asiento')),
                ('numeroAsiento', models.CharField(max_length=50, unique=True, verbose_name='Número de Asiento')),
                ('fechaAsiento', models.DateField(verbose_name='Fecha del Asiento')),
                ('conceptoAsiento', models.TextField(verbose_name='Concepto del Asiento')),
                ('fechaAsientoDigital', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación Digital')),
                ('idPeriodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='periodoContable.periodocontable', verbose_name='Periodo Contable')),
            ],
            options={
                'verbose_name': 'Asiento Contable',
                'verbose_name_plural': 'Asientos Contables',
                'ordering': ['fechaAsiento', 'numeroAsiento'],
            },
        ),
        migrations.CreateModel(
            name='DetalleAsiento',
            fields=[
                ('idDetalle', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Detalle')),
                ('debe', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Debe')),
                ('haber', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Haber')),
                ('estadoDetalle', models.BooleanField(default=True, verbose_name='Estado Activo')),
                ('fechaDetalle', models.DateField(auto_now_add=True, verbose_name='Fecha del Detalle')),
                ('idAsiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='asientoContable.asientocontable', verbose_name='Asiento Contable')),
                ('idPlanCuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planCuenta.plancuenta', verbose_name='Plan de Cuenta')),
            ],
            options={
                'verbose_name': 'Detalle de Asiento',
                'verbose_name_plural': 'Detalles de Asiento',
                'ordering': ['idAsiento', 'idDetalle'],
            },
        ),
    ]
