# Generated by Django 5.1.6 on 2025-11-09 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asientoContable', '0001_initial'),
        ('home', '0007_requisito_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleasiento',
            name='idMoneda',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.moneda', verbose_name='Moneda'),
            preserve_default=False,
        ),
    ]
