# Generated by Django 5.1.6 on 2025-11-11 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asientoContable', '0001_initial'),
        ('home', '0001_initial'),
        ('planCuenta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleasiento',
            name='idMoneda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.moneda', verbose_name='Moneda'),
        ),
        migrations.AddField(
            model_name='detalleasiento',
            name='idPlanCuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planCuenta.plancuenta', verbose_name='Plan de Cuenta'),
        ),
    ]
