# Generated by Django 5.1.6 on 2025-04-17 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '__first__'),
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Honorario',
            fields=[
                ('idHonorario', models.AutoField(primary_key=True, serialize=False)),
                ('horas', models.FloatField()),
                ('estadoHonorario', models.CharField(max_length=10)),
                ('fechaHonorario', models.DateField(auto_now_add=True)),
                ('idCargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.cargo')),
                ('idCohorte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.cohorte')),
                ('idMateria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.materia')),
                ('idPersona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.personas')),
            ],
            options={
                'verbose_name': 'Honorario',
                'verbose_name_plural': 'Honorarios',
            },
        ),
    ]
