# Generated by Django 5.1.6 on 2025-05-12 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Honorario',
            fields=[
                ('idHonorario', models.AutoField(primary_key=True, serialize=False)),
                ('horas', models.FloatField()),
                ('estadoHonorario', models.CharField(db_index=True, max_length=10)),
                ('fechaHonorario', models.DateField(auto_now_add=True)),
                ('idCargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.cargo')),
                ('idCohorte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.cohorte')),
                ('idMateria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.materia')),
                ('idPersona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.personas')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('idPersona', 'idMateria', 'idCohorte', 'horas'), name='unique_honorario_per_persona_materia_cohorte_horas')],
            },
        ),
    ]
