# Generated by Django 5.1.6 on 2025-05-11 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_tasa_idmoneda'),
        ('honorario', '0001_initial'),
        ('persona', '0002_alter_personas_cedula_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='honorario',
            options={},
        ),
        migrations.AddConstraint(
            model_name='honorario',
            constraint=models.UniqueConstraint(fields=('idPersona', 'idMateria', 'idCohorte', 'horas'), name='unique_honorario_per_persona_materia_cohorte_horas'),
        ),
    ]
