# Generated by Django 5.1.6 on 2025-06-07 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('honorario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='honorario',
            options={'verbose_name': 'Honorario', 'verbose_name_plural': 'Honorarios'},
        ),
    ]
