# Generated by Django 5.1.6 on 2025-11-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honorario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='honorario',
            name='estadoPago',
            field=models.CharField(db_index=True, default='PENDIENTE', max_length=10),
        ),
    ]
