# Generated by Django 5.1.6 on 2025-05-12 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honorario', '0002_alter_honorario_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='honorario',
            name='estadoHonorario',
            field=models.CharField(db_index=True, max_length=10),
        ),
    ]
