# Generated by Django 5.1.6 on 2025-06-04 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honorario', '0002_remove_honorario_unique_honorario_per_persona_materia_cohorte_horas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='honorario',
            name='fechaHonorario',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
