# Generated by Django 5.1.6 on 2025-05-25 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honorario', '0003_alter_honorario_estadohonorario'),
    ]

    operations = [
        migrations.AddField(
            model_name='honorario',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
            preserve_default=False,
        ),
    ]
