# Generated by Django 5.1.6 on 2025-06-04 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('honorario', '0004_alter_honorario_options_and_more'),
        ('persona', '0003_alter_personas_cedula'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='honorario',
            name='unique_honorario_per_persona_materia_cohorte_fecha',
        ),
        migrations.AddConstraint(
            model_name='honorario',
            constraint=models.UniqueConstraint(fields=('idPersona', 'idMateria', 'idCohorte', 'fechaHonorario', 'monto', 'estadoHonorario'), name='unique_honorario_per_persona_materia_cohorte_fecha'),
        ),
    ]
