# Generated by Django 5.1.6 on 2025-05-26 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honorario', '0004_honorario_monto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='honorario',
            name='horas',
            field=models.PositiveIntegerField(),
        ),
    ]
