# Generated by Django 5.1.6 on 2025-05-29 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asientoContable', '0001_initial'),
        ('cuentaBanco', '0001_initial'),
        ('empresa', '0001_initial'),
        ('home', '0001_initial'),
        ('periodoContable', '0001_initial'),
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('idFactura', models.AutoField(primary_key=True, serialize=False)),
                ('numeroFactura', models.CharField(max_length=50)),
                ('codigoControl', models.CharField(blank=True, max_length=50, null=True)),
                ('fechaEmision', models.DateField()),
                ('fechaVencimiento', models.DateField(blank=True, null=True)),
                ('formaPago', models.CharField(max_length=50)),
                ('plazoCredito', models.IntegerField(blank=True, null=True)),
                ('subtotalExento', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('subtotalGravado', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ivaRetenido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('descuento', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('totalVenta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(default='Pendiente', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaActualizacion', models.DateTimeField(auto_now=True)),
                ('idAsiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asientoContable.asientocontable')),
                ('idEmpresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa')),
                ('idPeriodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='periodoContable.periodocontable')),
                ('idPersona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.personas')),
                ('idTasa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.tasa')),
            ],
        ),
        migrations.CreateModel(
            name='FacturaDetalle',
            fields=[
                ('idDetalle', models.AutoField(primary_key=True, serialize=False)),
                ('tipoItem', models.CharField(max_length=50)),
                ('idReferencia', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precioUnitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('exento', models.BooleanField(default=False)),
                ('descuentoItem', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ivaItem', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('totalItem', models.DecimalField(decimal_places=2, max_digits=10)),
                ('idFactura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='factura.factura')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('idPago', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fechaPago', models.DateField()),
                ('formaPago', models.CharField(max_length=50)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('tasaCambio', models.DecimalField(decimal_places=4, default=1.0, max_digits=10)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fechaRegistro', models.DateTimeField(auto_now_add=True)),
                ('idAsiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asientoContable.asientocontable')),
                ('idCuentaBanco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuentaBanco.cuentabanco')),
                ('idFactura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='factura.factura')),
                ('idMoneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.moneda')),
            ],
        ),
    ]
