# Generated by Django 5.1.6 on 2025-07-15 02:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asientoContable', '0001_initial'),
        ('empresa', '0001_initial'),
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroFactura', models.CharField(max_length=50, unique=True)),
                ('fechaEmision', models.DateField(default=django.utils.timezone.now)),
                ('estado', models.CharField(default='PENDIENTE', max_length=20)),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
            },
        ),
        migrations.CreateModel(
            name='NotaRelacionada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('idPago', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fechaPago', models.DateField()),
                ('formaPago', models.CharField(max_length=50)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fechaRegistro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParametroTributario',
            fields=[
                ('idPT', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('IVA_GENERAL', 'IVA General'), ('IVA_EXENTO', 'IVA Exento'), ('IVA_RETENIDO_SERVICIOS', 'Retención IVA para servicios'), ('IVA_RETENIDO_COMPRAS', 'Retención IVA para compras'), ('ISLR_HONORARIOS', 'Retención ISLR honorarios'), ('ISLR_SERVICIOS', 'Retención ISLR servicios generales'), ('ISLR_COMPRAS', 'Retención ISLR compras'), ('MONTO_EXENCION_ISLR', 'Monto mínimo para retención ISLR'), ('MONTO_EXENCION_IVA', 'Monto mínimo para aplicación de IVA'), ('TASA_MUNICIPAL', 'Tasa municipal')], max_length=30)),
                ('aplica_a', models.CharField(choices=[('HONORARIO_PROFESOR', 'Honorarios Profesionales'), ('SERVICIO_GENERAL', 'Servicios Generales'), ('COMPRA_BIENES', 'Compra de Bienes'), ('INSCRIPCION', 'Inscripción'), ('SOLICITUD', 'Solicitud de Trámites')], help_text='Tipo de factura al que aplica este parámetro', max_length=20, verbose_name='Aplica a')),
                ('porcentaje', models.DecimalField(decimal_places=2, help_text='Porcentaje a aplicar (0 para exenciones)', max_digits=5)),
                ('valor_fijo', models.DecimalField(blank=True, decimal_places=2, help_text='Valor fijo (si aplica, en lugar de porcentaje)', max_digits=10, null=True)),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio de vigencia')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de fin de vigencia')),
                ('activo', models.BooleanField(default=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Parámetro Tributario',
                'verbose_name_plural': 'Parámetros Tributarios',
                'ordering': ['tipo', 'aplica_a', '-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='PlanArticulo',
            fields=[
                ('idPlanArti', models.AutoField(primary_key=True, serialize=False)),
                ('tipoArticulo', models.CharField(choices=[('HONORARIO_PROFESOR', 'Pagos a Proveedores - Honorarios Profesionales'), ('SERVICIO_GENERAL', 'Pagos a Proveedores - Servicios Generales (Internet, Luz, etc.)'), ('COMPRA_BIENES', 'Pagos a Proveedores - Compra de Bienes/Materiales'), ('INSCRIPCION', 'Ingresos de Estudiantes - Inscripción'), ('CUOTA', 'Ingresos de Estudiantes - Cuota'), ('SOLICITUD', 'Ingresos de Estudiantes - Solicitud de Trámites')], max_length=50)),
                ('tipo', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de inicio')),
            ],
        ),
        migrations.CreateModel(
            name='FacturaDetalle',
            fields=[
                ('idDetalle', models.AutoField(primary_key=True, serialize=False)),
                ('tipoItem', models.CharField(max_length=90)),
                ('descripcion', models.TextField()),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precioUnitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('exento', models.BooleanField(default=False)),
                ('descuentoItem', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ivaItem', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('totalItem', models.DecimalField(decimal_places=2, max_digits=10)),
                ('idFactura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='factura.factura')),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('idNota', models.AutoField(primary_key=True, serialize=False)),
                ('tipoOperacion', models.CharField(choices=[('COBRO', 'Nota de Cobro'), ('PAGO', 'Nota de Pago')], editable=False, max_length=10)),
                ('tipoArticulo', models.CharField(choices=[('HONORARIO_PROFESOR', 'Pagos a Proveedores - Honorarios Profesionales'), ('SERVICIO_GENERAL', 'Pagos a Proveedores - Servicios Generales (Internet, Luz, etc.)'), ('COMPRA_BIENES', 'Pagos a Proveedores - Compra de Bienes/Materiales'), ('INSCRIPCION', 'Ingresos de Estudiantes - Inscripción'), ('CUOTA', 'Ingresos de Estudiantes - Cuota'), ('SOLICITUD', 'Ingresos de Estudiantes - Solicitud de Trámites')], max_length=50)),
                ('numeroNota', models.CharField(max_length=50)),
                ('fechaEmision', models.DateField()),
                ('fechaVencimiento', models.DateField(blank=True, null=True)),
                ('formaPago', models.CharField(max_length=50)),
                ('plazoCredito', models.IntegerField(blank=True, null=True)),
                ('subtotalExento', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('subtotalGravado', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ivaRetenido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('islrRetenido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('descuento', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('totalNota', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(default='PENDIENTE', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaActualizacion', models.DateTimeField(auto_now=True)),
                ('idAsiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asientoContable.asientocontable', verbose_name='Asiento Contable')),
                ('idEmpresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa')),
                ('idPersona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='persona.personas')),
            ],
        ),
    ]
