# Generated by Django 5.1.6 on 2025-05-31 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='tipoFactura',
            field=models.CharField(choices=[('HONORARIO_PROFESOR', 'Pagos a Proveedores - Honorarios Profesionales'), ('SERVICIO_GENERAL', 'Pagos a Proveedores - Servicios Generales (Internet, Luz, etc.)'), ('COMPRA_BIENES', 'Pagos a Proveedores - Compra de Bienes/Materiales'), ('INSCRIPCION', 'Ingresos de Estudiantes - Inscripción'), ('SOLICITUD', 'Ingresos de Estudiantes - Solicitud de Trámites')], max_length=50),
        ),
        migrations.CreateModel(
            name='ParametroTributario',
            fields=[
                ('idPT', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('IVA_GENERAL', 'IVA General'), ('IVA_EXENTO', 'IVA Exento'), ('IVA_RETENIDO_SERVICIOS', 'Retención IVA para servicios'), ('IVA_RETENIDO_COMPRAS', 'Retención IVA para compras'), ('ISLR_HONORARIOS', 'Retención ISLR honorarios'), ('ISLR_SERVICIOS', 'Retención ISLR servicios generales'), ('ISLR_COMPRAS', 'Retención ISLR compras'), ('MONTO_EXENCION_ISLR', 'Monto mínimo para retención ISLR'), ('MONTO_EXENCION_IVA', 'Monto mínimo para aplicación de IVA'), ('TASA_MUNICIPAL', 'Tasa municipal')], max_length=30)),
                ('aplica_a', models.CharField(choices=[('HONORARIO_PROFESOR', 'Honorarios Profesionales'), ('SERVICIO_GENERAL', 'Servicios Generales'), ('COMPRA_BIENES', 'Compra de Bienes'), ('INSCRIPCION', 'Inscripción'), ('SOLICITUD', 'Solicitud de Trámites')], help_text='Tipo de factura al que aplica este parámetro', max_length=20, verbose_name='Aplica a')),
                ('porcentaje', models.DecimalField(decimal_places=2, help_text='Porcentaje a aplicar (0 para exenciones)', max_digits=5)),
                ('valor_fijo', models.DecimalField(blank=True, decimal_places=2, help_text='Valor fijo (si aplica, en lugar de porcentaje)', max_digits=10, null=True)),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio de vigencia')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de fin de vigencia')),
                ('activo', models.BooleanField(default=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Parámetro Tributario',
                'verbose_name_plural': 'Parámetros Tributarios',
                'ordering': ['tipo', 'aplica_a', '-fecha_inicio'],
                'unique_together': {('tipo', 'aplica_a', 'fecha_inicio')},
            },
        ),
    ]
