# Generated by Django 5.1.6 on 2025-07-12 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentaBanco', '0002_initial'),
        ('factura', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='idCuentaBanco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cuentaBanco.cuentabanco'),
        ),
    ]
