# Generated by Django 5.1.6 on 2025-06-08 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='idMoneda',
        ),
    ]
