# Generated by Django 5.1.6 on 2025-06-04 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asientoContable', '0001_initial'),
        ('cuentaBanco', '0002_initial'),
        ('factura', '0001_initial'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='idTasa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.tasa'),
        ),
        migrations.AddField(
            model_name='facturadetalle',
            name='idFactura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='factura.factura'),
        ),
        migrations.AddField(
            model_name='pago',
            name='idAsiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asientoContable.asientocontable'),
        ),
        migrations.AddField(
            model_name='pago',
            name='idCuentaBanco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuentaBanco.cuentabanco'),
        ),
        migrations.AddField(
            model_name='pago',
            name='idFactura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='factura.factura'),
        ),
        migrations.AddField(
            model_name='pago',
            name='idMoneda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.moneda'),
        ),
        migrations.AlterUniqueTogether(
            name='parametrotributario',
            unique_together={('tipo', 'aplica_a', 'fecha_inicio')},
        ),
    ]
