# Generated by Django 5.2.8 on 2025-11-23 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asientoContable', '0002_initial'),
        ('cuentaBanco', '0002_initial'),
        ('factura', '0001_initial'),
        ('home', '0001_initial'),
        ('honorario', '0001_initial'),
        ('inscripcion', '0001_initial'),
        ('planCuenta', '0001_initial'),
        ('solicitud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='idTasa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.tasa'),
        ),
        migrations.AddField(
            model_name='facturadetalle',
            name='idNota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_factura', to='factura.nota'),
        ),
        migrations.AddField(
            model_name='factura',
            name='nota',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='factura', to='factura.nota'),
        ),
        migrations.AddField(
            model_name='notarelacionada',
            name='idCuota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas', to='inscripcion.inscripcioncuota'),
        ),
        migrations.AddField(
            model_name='notarelacionada',
            name='idHonorario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas', to='honorario.honorario'),
        ),
        migrations.AddField(
            model_name='notarelacionada',
            name='idInscripcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas', to='inscripcion.inscripcion'),
        ),
        migrations.AddField(
            model_name='notarelacionada',
            name='idNota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaciones', to='factura.nota'),
        ),
        migrations.AddField(
            model_name='notarelacionada',
            name='idSolicitud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas', to='solicitud.solicitud'),
        ),
        migrations.AddField(
            model_name='pago',
            name='idAsiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asientoContable.asientocontable'),
        ),
        migrations.AddField(
            model_name='pago',
            name='idCuentaBanco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cuentaBanco.cuentabanco'),
        ),
        migrations.AddField(
            model_name='pago',
            name='idNota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='factura.nota'),
        ),
        migrations.AddField(
            model_name='pago',
            name='idTasa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.tasa'),
        ),
        migrations.AddField(
            model_name='pagoigtf',
            name='idPago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='igtf_pago', to='factura.pago'),
        ),
        migrations.AddField(
            model_name='pagotemporal',
            name='idCuentaBanco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cuentaBanco.cuentabanco'),
        ),
        migrations.AddField(
            model_name='pagotemporal',
            name='idNota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_temporales', to='factura.nota'),
        ),
        migrations.AddField(
            model_name='pagotemporal',
            name='idTasa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.tasa'),
        ),
        migrations.AlterUniqueTogether(
            name='parametrotributario',
            unique_together={('tipo', 'aplica_a', 'fecha_inicio')},
        ),
        migrations.AddField(
            model_name='planarticulo',
            name='idPlanCuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planCuenta.plancuenta', verbose_name='Plan de Cuenta'),
        ),
    ]
