# Generated by Django 5.1.6 on 2025-06-22 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pago',
            old_name='idFactura',
            new_name='idNota',
        ),
    ]
