# Generated by Django 5.1.6 on 2025-05-28 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0001_initial'),
        ('home', '0010_alter_tasa_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='idMoneda',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='tasaCambio',
        ),
        migrations.AddField(
            model_name='factura',
            name='idTasa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.tasa'),
            preserve_default=False,
        ),
    ]
