# Generated by Django 5.1.6 on 2025-10-05 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='monto',
            field=models.DecimalField(decimal_places=4, max_digits=60),
        ),
    ]
