# Generated by Django 5.1.6 on 2025-07-06 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0002_initial'),
        ('honorario', '0001_initial'),
        ('inscripcion', '0005_delete_pagocuota'),
        ('solicitud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaRelacionada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idHonorario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas', to='honorario.honorario')),
                ('idInscripcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas', to='inscripcion.inscripcion')),
                ('idNota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaciones', to='factura.nota')),
                ('idSolicitud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas', to='solicitud.solicitud')),
            ],
        ),
    ]
