# Generated by Django 5.1.6 on 2025-05-28 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0002_remove_factura_idmoneda_remove_factura_tasacambio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='totalDivisas',
        ),
    ]
