# Generated by Django 5.1.6 on 2025-07-12 07:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0002_alter_pago_idcuentabanco'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factura',
            options={'verbose_name': 'Factura', 'verbose_name_plural': 'Facturas'},
        ),
        migrations.RemoveField(
            model_name='factura',
            name='descuento',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='fechaActualizacion',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='fechaCreacion',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='idEmpresa',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='idFactura',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='idPersona',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='islrRetenido',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='iva',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='ivaRetenido',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='notas',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='subtotalExento',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='subtotalGravado',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='tipoFactura',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='totalVenta',
        ),
        migrations.AddField(
            model_name='factura',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factura',
            name='nota',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='factura', to='factura.nota'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='factura',
            name='estado',
            field=models.CharField(default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fechaEmision',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
