# Generated by Django 5.1.6 on 2025-06-22 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0002_rename_idfactura_pago_idnota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='idNota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='factura.nota'),
        ),
    ]
