# Generated by Django 5.1.6 on 2025-06-08 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0002_remove_pago_idmoneda'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='tasaCambio',
        ),
        migrations.AddField(
            model_name='pago',
            name='idTasa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.tasa'),
            preserve_default=False,
        ),
    ]
