# Generated by Django 5.1.6 on 2025-06-08 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asientoContable', '0001_initial'),
        ('factura', '0003_remove_pago_tasacambio_pago_idtasa'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='idAsiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asientoContable.asientocontable', verbose_name='Asiento Contable'),
        ),
    ]
