# Generated by Django 5.1.6 on 2025-10-13 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0003_alter_pago_monto'),
        ('inscripcion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notarelacionada',
            name='idCuota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas', to='inscripcion.inscripcioncuota'),
        ),
    ]
