# Generated by Django 5.1.6 on 2025-07-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0003_alter_factura_options_remove_factura_descuento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='monto',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
