# Generated by Django 5.1.6 on 2025-07-06 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0003_notarelacionada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nota',
            name='codigoControl',
        ),
        migrations.RemoveField(
            model_name='nota',
            name='tipoFactura',
        ),
        migrations.AlterField(
            model_name='nota',
            name='tipoNota',
            field=models.CharField(choices=[('HONORARIO_PROFESOR', 'Pagos a Proveedores - Honorarios Profesionales'), ('SERVICIO_GENERAL', 'Pagos a Proveedores - Servicios Generales (Internet, Luz, etc.)'), ('COMPRA_BIENES', 'Pagos a Proveedores - Compra de Bienes/Materiales'), ('INSCRIPCION', 'Ingresos de Estudiantes - Inscripción'), ('CUOTA', 'Ingresos de Estudiantes - Cuota'), ('SOLICITUD', 'Ingresos de Estudiantes - Solicitud de Trámites')], max_length=50),
        ),
    ]
