# Generated by Django 5.1.6 on 2025-07-14 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0004_alter_pago_monto'),
        ('planCuenta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='PlanArticulo',
            fields=[
                ('idPlanArti', models.AutoField(primary_key=True, serialize=False)),
                ('tipoArticulo', models.CharField(choices=[('HONORARIO_PROFESOR', 'Pagos a Proveedores - Honorarios Profesionales'), ('SERVICIO_GENERAL', 'Pagos a Proveedores - Servicios Generales (Internet, Luz, etc.)'), ('COMPRA_BIENES', 'Pagos a Proveedores - Compra de Bienes/Materiales'), ('INSCRIPCION', 'Ingresos de Estudiantes - Inscripción'), ('CUOTA', 'Ingresos de Estudiantes - Cuota'), ('SOLICITUD', 'Ingresos de Estudiantes - Solicitud de Trámites')], max_length=50)),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha de inicio')),
                ('idPlanCuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planCuenta.plancuenta', verbose_name='Plan de Cuenta')),
            ],
        ),
    ]
