# Generated by Django 5.1.6 on 2025-07-12 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0004_alter_pago_monto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
