# Generated by Django 5.1.6 on 2025-07-07 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0004_remove_nota_codigocontrol_remove_nota_tipofactura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='tipoArticulo',
            field=models.CharField(choices=[('HONORARIO_PROFESOR', 'Pagos a Proveedores - Honorarios Profesionales'), ('SERVICIO_GENERAL', 'Pagos a Proveedores - Servicios Generales (Internet, Luz, etc.)'), ('COMPRA_BIENES', 'Pagos a Proveedores - Compra de Bienes/Materiales'), ('INSCRIPCION', 'Ingresos de Estudiantes - Inscripción'), ('CUOTA', 'Ingresos de Estudiantes - Cuota'), ('SOLICITUD', 'Ingresos de Estudiantes - Solicitud de Trámites')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nota',
            name='tipoNota',
            field=models.CharField(choices=[('COBRO', 'Nota de Cobro'), ('PAGO', 'Nota de Pago')], editable=False, max_length=10),
        ),
    ]
