# Generated by Django 5.1.6 on 2025-10-26 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentaBanco', '0002_initial'),
        ('factura', '0004_alter_notarelacionada_idcuota'),
        ('home', '0004_alter_cohorte_nombrecohorte'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoTemporal',
            fields=[
                ('idPagoTemporal', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=4, max_digits=60)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fechaPago', models.DateTimeField(auto_now_add=True)),
                ('confirmado', models.BooleanField(default=False, help_text='Indica si el pago ha sido confirmado')),
                ('idCuentaBanco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cuentaBanco.cuentabanco')),
                ('idNota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_temporales', to='factura.nota')),
                ('idTasa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.tasa')),
            ],
        ),
    ]
