# Generated by Django 5.1.6 on 2025-07-14 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0005_alter_pago_monto_planarticulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='planarticulo',
            name='debe',
            field=models.BooleanField(default=False),
        ),
    ]
