# Generated by Django 5.1.6 on 2025-07-07 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0005_nota_tipoarticulo_alter_nota_tiponota'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nota',
            old_name='tipoNota',
            new_name='tipoOperacion',
        ),
    ]
