# Generated by Django 5.1.6 on 2025-11-15 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0005_pagotemporal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='tipoArticulo',
            field=models.CharField(choices=[('HONORARIO_PROFESOR', 'Pagos a Proveedores - Honorarios Profesionales'), ('SERVICIO_GENERAL', 'Pagos a Proveedores - Servicios Generales (Internet, Luz, etc.)'), ('COMPRA_BIENES', 'Pagos a Proveedores - Compra de Bienes/Materiales'), ('INSCRIPCION', 'Ingresos de Estudiantes - Inscripción'), ('CUOTA', 'Ingresos de Estudiantes - Cuota'), ('SOLICITUD', 'Ingresos de Estudiantes - Solicitud de Trámites'), ('IGTF', 'Impuesto a las Grandes Transacciones Financieras')], max_length=50),
        ),
        migrations.AlterField(
            model_name='parametrotributario',
            name='aplica_a',
            field=models.CharField(choices=[('PAGO', 'Pago'), ('COBRO', 'Cobro'), ('HONORARIO_PROFESOR', 'Honorarios Profesionales'), ('SERVICIO_GENERAL', 'Servicios Generales'), ('COMPRA_BIENES', 'Compra de Bienes'), ('INSCRIPCION', 'Inscripción'), ('SOLICITUD', 'Solicitud de Trámites')], help_text='Tipo de factura al que aplica este parámetro', max_length=20, verbose_name='Aplica a'),
        ),
        migrations.AlterField(
            model_name='parametrotributario',
            name='tipo',
            field=models.CharField(choices=[('IVA_GENERAL', 'IVA General'), ('IVA_EXENTO', 'IVA Exento'), ('IVA_RETENIDO_SERVICIOS', 'Retención IVA para servicios'), ('IVA_RETENIDO_COMPRAS', 'Retención IVA para compras'), ('ISLR_HONORARIOS', 'Retención ISLR honorarios'), ('ISLR_SERVICIOS', 'Retención ISLR servicios generales'), ('ISLR_COMPRAS', 'Retención ISLR compras'), ('MONTO_EXENCION_ISLR', 'Monto mínimo para retención ISLR'), ('MONTO_EXENCION_IVA', 'Monto mínimo para aplicación de IVA'), ('IGTF_NACIONAL_VENTAS_EFECTIVO', 'IGTF Nacional - Ventas en efectivo'), ('IGTF_NACIONAL_VENTAS_DIGITAL', 'IGTF Nacional - Ventas digitales'), ('IGTF_DIVISA_COMPRAS_EFECTIVO', 'IGTF Divisa - Compras en efectivo'), ('IGTF_DIVISA_COMPRAS_DIGITAL', 'IGTF Divisa - Compras digitales'), ('TASA_MUNICIPAL', 'Tasa municipal')], max_length=30),
        ),
        migrations.AlterField(
            model_name='planarticulo',
            name='tipoArticulo',
            field=models.CharField(choices=[('HONORARIO_PROFESOR', 'Pagos a Proveedores - Honorarios Profesionales'), ('SERVICIO_GENERAL', 'Pagos a Proveedores - Servicios Generales (Internet, Luz, etc.)'), ('COMPRA_BIENES', 'Pagos a Proveedores - Compra de Bienes/Materiales'), ('INSCRIPCION', 'Ingresos de Estudiantes - Inscripción'), ('CUOTA', 'Ingresos de Estudiantes - Cuota'), ('SOLICITUD', 'Ingresos de Estudiantes - Solicitud de Trámites'), ('IGTF', 'Impuesto a las Grandes Transacciones Financieras')], max_length=50),
        ),
    ]
