# Generated by Django 5.1.6 on 2025-07-10 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0006_rename_tiponota_nota_tipooperacion'),
        ('home', '0004_alter_cuotaformacion_fechacuota'),
    ]

    operations = [
        migrations.AddField(
            model_name='notarelacionada',
            name='idCuota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas', to='home.cuotaformacion'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='estado',
            field=models.CharField(default='PENDIENTE', max_length=20),
        ),
    ]
