# Generated by Django 5.1.6 on 2025-07-14 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0006_planarticulo_debe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planarticulo',
            old_name='debe',
            new_name='tipo',
        ),
    ]
