# Generated by Django 5.1.6 on 2025-11-15 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0006_alter_nota_tipoarticulo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='tipoArticulo',
            field=models.CharField(choices=[('HONORARIO_PROFESOR', 'Pagos a Proveedores - Honorarios Profesionales'), ('SERVICIO_GENERAL', 'Pagos a Proveedores - Servicios Generales (Internet, Luz, etc.)'), ('COMPRA_BIENES', 'Pagos a Proveedores - Compra de Bienes/Materiales'), ('INSCRIPCION', 'Ingresos de Estudiantes - Inscripción'), ('CUOTA', 'Ingresos de Estudiantes - Cuota'), ('SOLICITUD', 'Ingresos de Estudiantes - Solicitud de Trámites'), ('IGTF', 'Impuesto a las Grandes Transacciones Financieras (IGTF)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='planarticulo',
            name='tipoArticulo',
            field=models.CharField(choices=[('HONORARIO_PROFESOR', 'Pagos a Proveedores - Honorarios Profesionales'), ('SERVICIO_GENERAL', 'Pagos a Proveedores - Servicios Generales (Internet, Luz, etc.)'), ('COMPRA_BIENES', 'Pagos a Proveedores - Compra de Bienes/Materiales'), ('INSCRIPCION', 'Ingresos de Estudiantes - Inscripción'), ('CUOTA', 'Ingresos de Estudiantes - Cuota'), ('SOLICITUD', 'Ingresos de Estudiantes - Solicitud de Trámites'), ('IGTF', 'Impuesto a las Grandes Transacciones Financieras (IGTF)')], max_length=50),
        ),
    ]
