# Generated by Django 5.1.6 on 2025-08-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0007_rename_debe_planarticulo_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planarticulo',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de inicio'),
        ),
    ]
