# Generated by Django 5.1.6 on 2025-11-16 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0007_alter_nota_tipoarticulo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='igtfAplicado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='IGTF Aplicado'),
        ),
        migrations.CreateModel(
            name='PagoIGTF',
            fields=[
                ('idPagoIGTF', models.AutoField(primary_key=True, serialize=False)),
                ('tipoIGTF', models.CharField(choices=[('IGTF_NACIONAL_VENTAS_EFECTIVO', 'IGTF Nacional Ventas Efectivo'), ('IGTF_NACIONAL_VENTAS_DIGITAL', 'IGTF Nacional Ventas Digital'), ('IGTF_DIVISA_COMPRAS_EFECTIVO', 'IGTF Divisa Compras Efectivo'), ('IGTF_DIVISA_COMPRAS_DIGITAL', 'IGTF Divisa Compras Digital')], max_length=50)),
                ('montoIGTF', models.DecimalField(decimal_places=2, max_digits=10)),
                ('porcentajeIGTF', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('idPago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='igtf_pago', to='factura.pago')),
            ],
        ),
    ]
