# Generated by Django 5.1.6 on 2025-07-15 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0005_alter_pago_monto'),
        ('factura', '0007_rename_debe_planarticulo_tipo'),
    ]

    operations = [
    ]
