# Generated by Django 5.1.6 on 2025-11-20 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0008_nota_igtfaplicado_pagoigtf'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='estadoIGTF',
            field=models.CharField(default='NO_APLICA', max_length=20),
        ),
    ]
