# Generated by Django 5.1.6 on 2025-11-20 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0009_nota_estadoigtf'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='igtf',
            field=models.BooleanField(default=False),
        ),
    ]
