# Generated by Django 5.1.6 on 2025-11-22 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asientoContable', '0002_detalleasiento_idmoneda'),
        ('factura', '0010_pago_igtf'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='asiento_igtf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asiento_igtf', to='asientoContable.asientocontable', verbose_name='Asiento Contable IGTF'),
        ),
        migrations.AlterField(
            model_name='pagoigtf',
            name='tipoIGTF',
            field=models.CharField(choices=[('IGTF_NACIONAL_VENTAS_EFECTIVO', 'IGTF Nacional Ventas Efectivo'), ('IGTF_NACIONAL_VENTAS_DIGITAL', 'IGTF Nacional Ventas Digital'), ('IGTF_NACIONAL_COMPRAS_EFECTIVO', 'IGTF Nacional Compras Efectivo'), ('IGTF_NACIONAL_COMPRAS_DIGITAL', 'IGTF Nacional Compras Digital'), ('IGTF_DIVISA_COMPRAS_EFECTIVO', 'IGTF Divisa Compras Efectivo'), ('IGTF_DIVISA_COMPRAS_DIGITAL', 'IGTF Divisa Compras Digital'), ('IGTF_DIVISA_VENTAS_EFECTIVO', 'IGTF Divisa Ventas Efectivo'), ('IGTF_DIVISA_VENTAS_DIGITAL', 'IGTF Divisa Ventas Digital')], max_length=50),
        ),
    ]
