# Generated by Django 5.1.6 on 2025-07-14 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='empresa',
            fields=[
                ('idEmpresa', models.AutoField(primary_key=True, serialize=False)),
                ('nombreEmpresa', models.CharField(max_length=255)),
                ('rifEmpresa', models.CharField(max_length=20, unique=True)),
                ('direccionEmpresa', models.TextField()),
                ('telefonoEmpresa', models.CharField(max_length=15)),
                ('correoEmpresa', models.EmailField(max_length=254)),
                ('estadoEmpresa', models.BooleanField(default=True)),
                ('fechaEmpresa', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
